// Generates src/core/document-css.ts from src/styles/document.css so the default stylesheet can be
// imported as a plain string in every runtime (browser, Node, edge) without a bundler plugin.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(resolve(root, "src/styles/document.css"), "utf8");
const target = resolve(root, "src/core/document-css.ts");

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// Generated by scripts/gen-css.mjs from src/styles/document.css. Do not edit.\n` +
    `export const documentCss: string = ${JSON.stringify(css)};\n`,
);
